### ISSUE TITLE
Bug report: Build failing on the 'run the script' stage

### ISSUE THREAD

**Issue by lucchesi-rodrigo** [konfuzio-ai/ai-comedy-club#65]
### Prerequisites

- [x] I checked the [existing issues](https://github.com/konfuzio-ai/ai-comedy-club/issues) to make sure my problem has not already been reported.

### Expected Behavior

Pipeline must be working

### Current Behavior

While creating a patch to remove data from the .env file, I saw the Actions Pipeline failing on the build stage.

### To Reproduce

Check the Actions tab on the repository

### Context

The pipeline is breaking while executing the rosskost bot:

```
Could not find TensorRT
Fatal Python error: Aborted
```

### Failure Logs

```
  File "/opt/hostedtoolcache/Python/3.9.18/x64/bin/pytest", line 8 in <module>
Some weights of the model checkpoint at /home/runner/work/ai-comedy-club/ai-comedy-club/bots/rosskost/data/bert_tiny were not used when initializing BertForSequenceClassification: ['classifier.3.bias', 'classifier.0.bias', 'classifier.0.weight', 'classifier.3.weight']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at /home/runner/work/ai-comedy-club/ai-comedy-club/bots/rosskost/data/bert_tiny and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "/home/runner/work/ai-comedy-club/ai-comedy-club/main.py", line 38, in <module>
    bot = bot_module.Bot()
AttributeError: module 'bot' has no attribute 'Bot'
```

**Comment by lucchesi-rodrigo** [comment]
@atraining @rosskost

**Comment by atraining** [comment]
@lucchesi-rodrigo @rosskost 

 I did not have much time to have a look at it.

I was ducktaping it in the GibHub webinterface, which resulted in no success.

Do you see an option to support me or to fix it?

Relevant commits where I tried to fix it.

- https://github.com/konfuzio-ai/ai-comedy-club/commit/6efd45796794692e65e622c81d9abc2b1a6e35ae
- https://github.com/konfuzio-ai/ai-comedy-club/commit/8583e50cf1a1c2a4b9d27e719ff37e720d5cf19d
